### ISSUE TITLE
Create additional linting configuration for React Native

### ISSUE THREAD

**Issue by dennisschoepf** [digital-h-gmbh/devtools#2]
We also want to lint React Native code. These are the questions to answer before implementation:

- [ ] How do we want to write React Native code?
- [X] Are we already using eslint-react-native-plugins? -> No
- [X] Are there custom rules for React Native code we want to include? -> Yes, see Simon's answer
- [ ] How can we make an optionally installable ESLint React Native config? -> Create task if needed

If all of those questions are answered, a Pull Request can be opened with the implementation.

**Comment by hansen-simon** [comment]
I placed the new style configs into the fabucar project. [Checkout the changes](https://github.com/digital-h-gmbh/fabucar-pro/compare/feature/new-digital-h-coding-style-guidlines?expand=1#)


Points I see we should talk about: 
* should braces around a single arrow function argument be enforces like it is currenty? [example](https://github.com/digital-h-gmbh/fabucar-pro/compare/feature/new-digital-h-coding-style-guidlines?expand=1#diff-f8cd8c870d6047734d266677fa9705a5e88f6f0bf0656c8afc6eed744379c103L224-R228), [another example](https://github.com/digital-h-gmbh/fabucar-pro/compare/feature/new-digital-h-coding-style-guidlines?expand=1#diff-f8cd8c870d6047734d266677fa9705a5e88f6f0bf0656c8afc6eed744379c103R481)
* Should variable assignment in switch block be prohibited? In react apps redux is often used. Reducers are often implemented with switch case and quite some logic within. We could use it as option to clean them up, or we would need to change the rule. [example](https://github.com/digital-h-gmbh/fabucar-pro/compare/feature/new-digital-h-coding-style-guidlines?expand=1#diff-aeb64d151155fe746629a38bd6b68048cdee72b00a72e91e44cec27a4a58d7cc)
* How to handle 'usage before declaration' error? In ReactNative project we often have a component and a styles variable at the bottom. I personally like to have the styles at the bottom, instead of another file. But this order triggers the error. The rule is undoubtedly useful within a function, but not necessarily in the scope of a file.


> Are we already using eslint-react-native-plugins?

* nope, we currently extend [@react-native-community](https://www.npmjs.com/package/@react-native-community/eslint-config). But I think they are not using all features of eslint-react-native-plugins


> Are there custom rules for React Native code we want to include?

* "react-native/no-unused-styles": 2,
* "react-native/no-inline-styles": 2,
* "react-native/no-color-literals": 2,
* "react-native/no-single-element-style-arrays": 2,
seem to be sane options to me

> How can we make an optionally installable ESLint React Native config?

* good question. Maybe with an extra directory for react-native-eslint rules that extends somehow the beasic eslint rules?

**Comment by dennisschoepf** [comment]
@hansen-simon 

_should braces around a single arrow function argument be enforces like it is currenty? example, another example_

Doesn't matter to me as long as it is consistent (e.g. for one function param we never use braces, from two on we use them)

_Should variable assignment in switch block be prohibited?_

I don't think that prohibiting it creates as much value as it is work for already existing code. If we do want to prohibit it in the future, that might make sense though. A possible approach would be to default to prohibiting it and disabling (overwriting) manually for existing projects

_How to handle 'usage before declaration' error?_

True, I'll check if there is an option that throws an error for functions but not React Native styles, as I agree with your sentiment.

@pascalstockert @JensSpanier @SimonSchoetz @weiss-laura @pejotrich  what do you think?

**Comment by SimonSchoetz** [comment]
**should braces around a single arrow function argument be enforces like it is currenty?**

Having braces also around single arguments in functions helped me to understand it better at the beginning but now I like it more without them because it's simply less braces and we already have a ton of them. On the other hand having no braces is an indicator that no typescript specification is used and as I understand it, we want to specify as much as possible don't we?

**Should variable assignment in switch block be prohibited?**

I'm not sure about this at all. I feel like having declarations inside of a switch block is more secure because it's in scope of this switch case and so there is less of a chance to use a declared variable wrong or start mutating them for the sake of not having to declare a new variable which is used in different switch blocks but needs different values for each case.
Regarding the reducers or the structure of the Redux implementation in Fabucar in general: It's a mess. And I think I would've liked it more if each block in a switch case and their corresponding counterparts in saga etc. would be grouped together - which means these declarations would be in their own file and therefore in scope of their function anyway.

**How to handle 'usage before declaration' error?**

What Simon said

**Comment by dennisschoepf** [comment]
Created a new react-native config with custom rules described here. These are available from version 1.9.0 onwards
